# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_baza_popraw_ls.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(420, 230)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 15, 380, 22))
        self.label.setObjectName("label")
        self.lineEdit_bazy = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_bazy.setGeometry(QtCore.QRect(20, 50, 300, 26))
        self.lineEdit_bazy.setReadOnly(True)
        self.lineEdit_bazy.setObjectName("lineEdit_bazy")
        self.pushButton_bazy = QtWidgets.QPushButton(Dialog)
        self.pushButton_bazy.setGeometry(QtCore.QRect(330, 50, 70, 26))
        self.pushButton_bazy.setObjectName("pushButton_bazy")
        self.label_bazy = QtWidgets.QLabel(Dialog)
        self.label_bazy.setGeometry(QtCore.QRect(20, 85, 380, 22))
        self.label_bazy.setText("")
        self.label_bazy.setObjectName("label_bazy")
        self.checkBox_wszystkie = QtWidgets.QCheckBox(Dialog)
        self.checkBox_wszystkie.setGeometry(QtCore.QRect(20, 120, 380, 26))
        self.checkBox_wszystkie.setObjectName("checkBox_wszystkie")
        self.pushButton_ok = QtWidgets.QPushButton(Dialog)
        self.pushButton_ok.setGeometry(QtCore.QRect(110, 170, 99, 38))
        self.pushButton_ok.setEnabled(False)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.pushButton_porzuc = QtWidgets.QPushButton(Dialog)
        self.pushButton_porzuc.setGeometry(QtCore.QRect(230, 170, 99, 38))
        self.pushButton_porzuc.setObjectName("pushButton_porzuc")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Kontrola Ls w bazie"))
        self.label.setText(_translate("Dialog", "Sprawdź bazę/bazy pod kątem duplikatów Ls i zerowych powierzchni"))
        self.pushButton_bazy.setText(_translate("Dialog", "Wskaż..."))
        self.checkBox_wszystkie.setText(_translate("Dialog", "Sprawdzaj wszystkie użytki (nie tylko Ls)"))
        self.pushButton_ok.setText(_translate("Dialog", "OK"))
        self.pushButton_porzuc.setText(_translate("Dialog", "Porzuć"))
