# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_czysc_kolumny.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(373, 295)
        self.pushButton_ok = QtWidgets.QPushButton(Dialog)
        self.pushButton_ok.setGeometry(QtCore.QRect(80, 220, 99, 38))
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.pushButton_porzuc = QtWidgets.QPushButton(Dialog)
        self.pushButton_porzuc.setGeometry(QtCore.QRect(200, 220, 99, 38))
        self.pushButton_porzuc.setObjectName("pushButton_porzuc")
        self.checkBox_adrles = QtWidgets.QCheckBox(Dialog)
        self.checkBox_adrles.setGeometry(QtCore.QRect(60, 50, 97, 26))
        self.checkBox_adrles.setObjectName("checkBox_adrles")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(40, 20, 341, 22))
        self.label.setObjectName("label")
        self.checkBox_oddz = QtWidgets.QCheckBox(Dialog)
        self.checkBox_oddz.setGeometry(QtCore.QRect(60, 80, 97, 26))
        self.checkBox_oddz.setObjectName("checkBox_oddz")
        self.checkBox_wydz = QtWidgets.QCheckBox(Dialog)
        self.checkBox_wydz.setGeometry(QtCore.QRect(60, 110, 97, 26))
        self.checkBox_wydz.setObjectName("checkBox_wydz")
        self.checkBox_lz = QtWidgets.QCheckBox(Dialog)
        self.checkBox_lz.setEnabled(False)
        self.checkBox_lz.setGeometry(QtCore.QRect(190, 110, 111, 26))
        self.checkBox_lz.setObjectName("checkBox_lz")
        self.checkBox_oddz_warstwa = QtWidgets.QCheckBox(Dialog)
        self.checkBox_oddz_warstwa.setGeometry(QtCore.QRect(60, 180, 97, 26))
        self.checkBox_oddz_warstwa.setObjectName("checkBox_oddz_warstwa")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(40, 150, 341, 22))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog)
        self.checkBox_wydz.toggled['bool'].connect(self.checkBox_lz.setEnabled)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Czyszczenie kolumn w zaznaczonej warstwie"))
        self.pushButton_ok.setText(_translate("Dialog", "OK"))
        self.pushButton_porzuc.setText(_translate("Dialog", "Porzuć"))
        self.checkBox_adrles.setText(_translate("Dialog", "ADR_LES"))
        self.label.setText(_translate("Dialog", "Wyczyść kolumny w zaznaczonej warstwie"))
        self.checkBox_oddz.setText(_translate("Dialog", "ODDZ"))
        self.checkBox_wydz.setText(_translate("Dialog", "WYDZ"))
        self.checkBox_lz.setText(_translate("Dialog", "Wymaż Lz"))
        self.checkBox_oddz_warstwa.setText(_translate("Dialog", "ODDZ"))
        self.label_2.setText(_translate("Dialog", "Wyczyść kolumnę w  warstwie ODDZ"))
