# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_naklejki_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogNaklejki(object):
    def setupUi(self, DialogNaklejki):
        DialogNaklejki.setObjectName("DialogNaklejki")
        DialogNaklejki.resize(450, 427)
        DialogNaklejki.setMinimumSize(QtCore.QSize(450, 427))
        DialogNaklejki.setMaximumSize(QtCore.QSize(450, 427))
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogNaklejki)
        self.buttonBox.setGeometry(QtCore.QRect(350, 100, 81, 81))
        self.buttonBox.setMaximumSize(QtCore.QSize(81, 241))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.pushButton_wybierz = QtWidgets.QPushButton(DialogNaklejki)
        self.pushButton_wybierz.setGeometry(QtCore.QRect(360, 30, 75, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.pushButton_wybierz.setFont(font)
        self.pushButton_wybierz.setObjectName("pushButton_wybierz")
        self.lineEdit_sciezka = QtWidgets.QLineEdit(DialogNaklejki)
        self.lineEdit_sciezka.setGeometry(QtCore.QRect(10, 30, 341, 20))
        self.lineEdit_sciezka.setObjectName("lineEdit_sciezka")
        self.label = QtWidgets.QLabel(DialogNaklejki)
        self.label.setGeometry(QtCore.QRect(20, 10, 211, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(DialogNaklejki)
        self.label_2.setGeometry(QtCore.QRect(30, 160, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_od = QtWidgets.QLineEdit(DialogNaklejki)
        self.lineEdit_od.setGeometry(QtCore.QRect(40, 180, 111, 20))
        self.lineEdit_od.setObjectName("lineEdit_od")
        self.label_3 = QtWidgets.QLabel(DialogNaklejki)
        self.label_3.setGeometry(QtCore.QRect(20, 180, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(DialogNaklejki)
        self.label_4.setGeometry(QtCore.QRect(180, 180, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_do = QtWidgets.QLineEdit(DialogNaklejki)
        self.lineEdit_do.setGeometry(QtCore.QRect(210, 180, 111, 20))
        self.lineEdit_do.setObjectName("lineEdit_do")
        self.label_5 = QtWidgets.QLabel(DialogNaklejki)
        self.label_5.setGeometry(QtCore.QRect(10, 60, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.comboBox_typ = QtWidgets.QComboBox(DialogNaklejki)
        self.comboBox_typ.setGeometry(QtCore.QRect(160, 60, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_typ.setFont(font)
        self.comboBox_typ.setObjectName("comboBox_typ")
        self.comboBox_typ.addItem("")
        self.comboBox_typ.addItem("")
        self.checkBox_polacz = QtWidgets.QCheckBox(DialogNaklejki)
        self.checkBox_polacz.setEnabled(False)
        self.checkBox_polacz.setGeometry(QtCore.QRect(40, 100, 191, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_polacz.setFont(font)
        self.checkBox_polacz.setObjectName("checkBox_polacz")
        self.checkBox_tomy = QtWidgets.QCheckBox(DialogNaklejki)
        self.checkBox_tomy.setGeometry(QtCore.QRect(40, 130, 281, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_tomy.setFont(font)
        self.checkBox_tomy.setObjectName("checkBox_tomy")
        self.label_6 = QtWidgets.QLabel(DialogNaklejki)
        self.label_6.setGeometry(QtCore.QRect(30, 200, 361, 18))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setItalic(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.groupBox = QtWidgets.QGroupBox(DialogNaklejki)
        self.groupBox.setGeometry(QtCore.QRect(10, 360, 431, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.checkBox_plyta = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_plyta.setGeometry(QtCore.QRect(30, 30, 87, 22))
        self.checkBox_plyta.setChecked(True)
        self.checkBox_plyta.setObjectName("checkBox_plyta")
        self.checkBox_okladka = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_okladka.setGeometry(QtCore.QRect(170, 30, 87, 22))
        self.checkBox_okladka.setChecked(True)
        self.checkBox_okladka.setObjectName("checkBox_okladka")
        self.checkBox_naklejki = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_naklejki.setGeometry(QtCore.QRect(320, 30, 87, 22))
        self.checkBox_naklejki.setChecked(True)
        self.checkBox_naklejki.setObjectName("checkBox_naklejki")
        self.groupBox_2 = QtWidgets.QGroupBox(DialogNaklejki)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 230, 431, 131))
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_7 = QtWidgets.QLabel(self.groupBox_2)
        self.label_7.setGeometry(QtCore.QRect(20, 40, 41, 18))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_2)
        self.label_8.setGeometry(QtCore.QRect(20, 100, 51, 18))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setGeometry(QtCore.QRect(110, 100, 71, 18))
        self.label_9.setObjectName("label_9")
        self.lineEdit_herb = QtWidgets.QLineEdit(self.groupBox_2)
        self.lineEdit_herb.setGeometry(QtCore.QRect(60, 40, 271, 21))
        self.lineEdit_herb.setObjectName("lineEdit_herb")
        self.pushButton_herb = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_herb.setGeometry(QtCore.QRect(340, 40, 75, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.pushButton_herb.setFont(font)
        self.pushButton_herb.setObjectName("pushButton_herb")
        self.checkBox_pgllp = QtWidgets.QCheckBox(self.groupBox_2)
        self.checkBox_pgllp.setGeometry(QtCore.QRect(70, 100, 21, 22))
        self.checkBox_pgllp.setText("")
        self.checkBox_pgllp.setObjectName("checkBox_pgllp")
        self.comboBox_nfosigw = QtWidgets.QComboBox(self.groupBox_2)
        self.comboBox_nfosigw.setGeometry(QtCore.QRect(180, 90, 231, 32))
        self.comboBox_nfosigw.setObjectName("comboBox_nfosigw")
        self.comboBox_nfosigw.addItem("")
        self.comboBox_nfosigw.addItem("")
        self.comboBox_nfosigw.addItem("")
        self.comboBox_nfosigw.addItem("")
        self.comboBox_nfosigw.addItem("")
        self.comboBox_nfosigw.addItem("")
        self.comboBox_nfosigw.addItem("")
        self.comboBox_nfosigw.addItem("")
        self.comboBox_nfosigw.addItem("")
        self.comboBox_nfosigw.addItem("")
        self.comboBox_nfosigw.addItem("")
        self.comboBox_nfosigw.addItem("")
        self.comboBox_nfosigw.addItem("")
        self.comboBox_nfosigw.addItem("")
        self.comboBox_nfosigw.addItem("")
        self.comboBox_nfosigw.addItem("")
        self.comboBox_nfosigw.addItem("")
        self.label_10 = QtWidgets.QLabel(self.groupBox_2)
        self.label_10.setGeometry(QtCore.QRect(20, 60, 311, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setItalic(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")

        self.retranslateUi(DialogNaklejki)
        self.buttonBox.accepted.connect(DialogNaklejki.accept)
        self.buttonBox.rejected.connect(DialogNaklejki.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogNaklejki)

    def retranslateUi(self, DialogNaklejki):
        _translate = QtCore.QCoreApplication.translate
        DialogNaklejki.setWindowTitle(_translate("DialogNaklejki", "Podaj informacje do generowania naklejek"))
        self.pushButton_wybierz.setText(_translate("DialogNaklejki", "Wybierz"))
        self.label.setText(_translate("DialogNaklejki", "Katalog z bazami taksatora:"))
        self.label_2.setText(_translate("DialogNaklejki", "Stan na:"))
        self.lineEdit_od.setText(_translate("DialogNaklejki", "DD.MM.RRRR"))
        self.label_3.setText(_translate("DialogNaklejki", "od:"))
        self.label_4.setText(_translate("DialogNaklejki", "do:"))
        self.lineEdit_do.setText(_translate("DialogNaklejki", "DD.MM.RRRR"))
        self.label_5.setText(_translate("DialogNaklejki", "Typ opracowania:"))
        self.comboBox_typ.setItemText(0, _translate("DialogNaklejki", "UPUL"))
        self.comboBox_typ.setItemText(1, _translate("DialogNaklejki", "ISL"))
        self.checkBox_polacz.setText(_translate("DialogNaklejki", "Połączony dla całej gminy"))
        self.checkBox_tomy.setText(_translate("DialogNaklejki", "opracowania są podzielone na tomy"))
        self.label_6.setText(_translate("DialogNaklejki", "Stan geodezji zostanie podczytany z bazy TPU (tabela F_PARAMETER)"))
        self.groupBox.setTitle(_translate("DialogNaklejki", "Generuj"))
        self.checkBox_plyta.setText(_translate("DialogNaklejki", "płytkę"))
        self.checkBox_okladka.setText(_translate("DialogNaklejki", "okładkę"))
        self.checkBox_naklejki.setText(_translate("DialogNaklejki", "naklejki"))
        self.groupBox_2.setTitle(_translate("DialogNaklejki", "herb / dofinansowania"))
        self.label_7.setText(_translate("DialogNaklejki", "herb:"))
        self.label_8.setText(_translate("DialogNaklejki", "PGLLP:"))
        self.label_9.setText(_translate("DialogNaklejki", "NFOŚiGW:"))
        self.pushButton_herb.setText(_translate("DialogNaklejki", "Wybierz"))
        self.comboBox_nfosigw.setItemText(0, _translate("DialogNaklejki", "(Brak)"))
        self.comboBox_nfosigw.setItemText(1, _translate("DialogNaklejki", "Białystok (Podlaskie)"))
        self.comboBox_nfosigw.setItemText(2, _translate("DialogNaklejki", "Gdańsk (Pomorskie)"))
        self.comboBox_nfosigw.setItemText(3, _translate("DialogNaklejki", "Katowice (Śląskie)"))
        self.comboBox_nfosigw.setItemText(4, _translate("DialogNaklejki", "Kielce (Świętokrzyskie)"))
        self.comboBox_nfosigw.setItemText(5, _translate("DialogNaklejki", "Kraków (Małopolskie)"))
        self.comboBox_nfosigw.setItemText(6, _translate("DialogNaklejki", "Łódź (Łódzkie)"))
        self.comboBox_nfosigw.setItemText(7, _translate("DialogNaklejki", "Lublin (Lubelskie)"))
        self.comboBox_nfosigw.setItemText(8, _translate("DialogNaklejki", "Olsztyn (Warmińsko-Mazurskie)"))
        self.comboBox_nfosigw.setItemText(9, _translate("DialogNaklejki", "Opole (Opolskie)"))
        self.comboBox_nfosigw.setItemText(10, _translate("DialogNaklejki", "Poznań (Wielkopolskie)"))
        self.comboBox_nfosigw.setItemText(11, _translate("DialogNaklejki", "Rzeszów (Podkarpackie)"))
        self.comboBox_nfosigw.setItemText(12, _translate("DialogNaklejki", "Szczecin (Zachodnio-Pomorskie)"))
        self.comboBox_nfosigw.setItemText(13, _translate("DialogNaklejki", "Toruń (Kujawsko-Pomorskie)"))
        self.comboBox_nfosigw.setItemText(14, _translate("DialogNaklejki", "Warszawa (Mazowieckie)"))
        self.comboBox_nfosigw.setItemText(15, _translate("DialogNaklejki", "Wrocław (Dolnośląskie)"))
        self.comboBox_nfosigw.setItemText(16, _translate("DialogNaklejki", "Zielona Góra (Lubuskie)"))
        self.label_10.setText(_translate("DialogNaklejki", "Jeżeli w katalogu z bazami znajduje się plik:    herb.png \n"
"zostanie podczytany automatycznie"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogNaklejki = QtWidgets.QDialog()
    ui = Ui_DialogNaklejki()
    ui.setupUi(DialogNaklejki)
    DialogNaklejki.show()
    sys.exit(app.exec_())

