# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_sprawdz_ls.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(519, 342)
        Dialog.setMinimumSize(QtCore.QSize(519, 342))
        Dialog.setMaximumSize(QtCore.QSize(519, 342))
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 20, 101, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 101, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 101, 16))
        self.label_3.setObjectName("label_3")
        self.lineEdit_klu = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_klu.setGeometry(QtCore.QRect(130, 20, 281, 20))
        self.lineEdit_klu.setObjectName("lineEdit_klu")
        self.lineEdit_dzkat = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_dzkat.setGeometry(QtCore.QRect(130, 60, 281, 20))
        self.lineEdit_dzkat.setObjectName("lineEdit_dzkat")
        self.lineEdit_bazy = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_bazy.setGeometry(QtCore.QRect(130, 100, 281, 20))
        self.lineEdit_bazy.setObjectName("lineEdit_bazy")
        self.label_klu = QtWidgets.QLabel(Dialog)
        self.label_klu.setGeometry(QtCore.QRect(130, 40, 271, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setItalic(True)
        self.label_klu.setFont(font)
        self.label_klu.setText("")
        self.label_klu.setObjectName("label_klu")
        self.label_dzkat = QtWidgets.QLabel(Dialog)
        self.label_dzkat.setGeometry(QtCore.QRect(130, 80, 271, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setItalic(True)
        self.label_dzkat.setFont(font)
        self.label_dzkat.setText("")
        self.label_dzkat.setObjectName("label_dzkat")
        self.label_bazy = QtWidgets.QLabel(Dialog)
        self.label_bazy.setGeometry(QtCore.QRect(130, 120, 271, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setItalic(True)
        self.label_bazy.setFont(font)
        self.label_bazy.setText("")
        self.label_bazy.setObjectName("label_bazy")
        self.comboBox_wlas = QtWidgets.QComboBox(Dialog)
        self.comboBox_wlas.setGeometry(QtCore.QRect(130, 150, 361, 22))
        self.comboBox_wlas.setObjectName("comboBox_wlas")
        self.comboBox_wlas.addItem("")
        self.comboBox_wlas.addItem("")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 150, 101, 21))
        self.label_4.setObjectName("label_4")
        self.pushButton_klu = QtWidgets.QPushButton(Dialog)
        self.pushButton_klu.setGeometry(QtCore.QRect(420, 20, 75, 23))
        self.pushButton_klu.setObjectName("pushButton_klu")
        self.pushButton_dzkat = QtWidgets.QPushButton(Dialog)
        self.pushButton_dzkat.setGeometry(QtCore.QRect(420, 60, 75, 23))
        self.pushButton_dzkat.setObjectName("pushButton_dzkat")
        self.pushButton_bazy = QtWidgets.QPushButton(Dialog)
        self.pushButton_bazy.setGeometry(QtCore.QRect(420, 100, 75, 23))
        self.pushButton_bazy.setObjectName("pushButton_bazy")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 180, 171, 21))
        self.label_5.setObjectName("label_5")
        self.comboBox_ident = QtWidgets.QComboBox(Dialog)
        self.comboBox_ident.setEnabled(True)
        self.comboBox_ident.setGeometry(QtCore.QRect(170, 180, 321, 22))
        self.comboBox_ident.setEditable(False)
        self.comboBox_ident.setObjectName("comboBox_ident")
        self.comboBox_ident.addItem("")
        self.comboBox_ident.addItem("")
        self.comboBox_ident.addItem("")
        self.groupBox_adradm = QtWidgets.QGroupBox(Dialog)
        self.groupBox_adradm.setEnabled(False)
        self.groupBox_adradm.setGeometry(QtCore.QRect(10, 210, 211, 51))
        self.groupBox_adradm.setObjectName("groupBox_adradm")
        self.comboBox_landid = QtWidgets.QComboBox(self.groupBox_adradm)
        self.comboBox_landid.setGeometry(QtCore.QRect(10, 20, 191, 22))
        self.comboBox_landid.setObjectName("comboBox_landid")
        self.groupBox_kol = QtWidgets.QGroupBox(Dialog)
        self.groupBox_kol.setEnabled(False)
        self.groupBox_kol.setGeometry(QtCore.QRect(230, 210, 261, 81))
        self.groupBox_kol.setObjectName("groupBox_kol")
        self.label_6 = QtWidgets.QLabel(self.groupBox_kol)
        self.label_6.setGeometry(QtCore.QRect(10, 20, 111, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_kol)
        self.label_7.setGeometry(QtCore.QRect(10, 50, 111, 21))
        self.label_7.setObjectName("label_7")
        self.comboBox_au = QtWidgets.QComboBox(self.groupBox_kol)
        self.comboBox_au.setGeometry(QtCore.QRect(120, 20, 131, 22))
        self.comboBox_au.setObjectName("comboBox_au")
        self.comboBox_sq = QtWidgets.QComboBox(self.groupBox_kol)
        self.comboBox_sq.setGeometry(QtCore.QRect(120, 50, 131, 22))
        self.comboBox_sq.setObjectName("comboBox_sq")
        self.pushButton_ok = QtWidgets.QPushButton(Dialog)
        self.pushButton_ok.setEnabled(False)
        self.pushButton_ok.setGeometry(QtCore.QRect(90, 300, 201, 31))
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.pushButton_cancel = QtWidgets.QPushButton(Dialog)
        self.pushButton_cancel.setGeometry(QtCore.QRect(360, 300, 75, 31))
        self.pushButton_cancel.setObjectName("pushButton_cancel")

        self.retranslateUi(Dialog)
        self.pushButton_ok.clicked.connect(Dialog.hide)
        self.pushButton_cancel.clicked.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Przygotuj LS"))
        self.label.setText(_translate("Dialog", "Warstwa KLU:"))
        self.label_2.setText(_translate("Dialog", "Warstwa DZKAT:"))
        self.label_3.setText(_translate("Dialog", "Katalog z bazami:"))
        self.comboBox_wlas.setItemText(0, _translate("Dialog", "OF i współwłasności"))
        self.comboBox_wlas.setItemText(1, _translate("Dialog", "Wszystkie"))
        self.label_4.setText(_translate("Dialog", "Własność:"))
        self.pushButton_klu.setText(_translate("Dialog", "Wybierz"))
        self.pushButton_dzkat.setText(_translate("Dialog", "Wybierz"))
        self.pushButton_bazy.setText(_translate("Dialog", "Wybierz"))
        self.label_5.setText(_translate("Dialog", "Sposób identyfikacji użytków:"))
        self.comboBox_ident.setItemText(0, _translate("Dialog", "---"))
        self.comboBox_ident.setItemText(1, _translate("Dialog", "AU i SQ"))
        self.comboBox_ident.setItemText(2, _translate("Dialog", "LANDID (20020150012.AR_2.446/1_LsV)"))
        self.groupBox_adradm.setTitle(_translate("Dialog", "Kolumna z LANDID"))
        self.groupBox_kol.setTitle(_translate("Dialog", "Kolumny z AU i SQ"))
        self.label_6.setText(_translate("Dialog", "Kolumna z kodem AU:"))
        self.label_7.setText(_translate("Dialog", "Kolumna z kodem SQ:"))
        self.pushButton_ok.setText(_translate("Dialog", "OK"))
        self.pushButton_cancel.setText(_translate("Dialog", "Porzuć"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

