# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_sprawdz_dzkat.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(561, 378)
        self.pushButton_ok = QtWidgets.QPushButton(Dialog)
        self.pushButton_ok.setEnabled(False)
        self.pushButton_ok.setGeometry(QtCore.QRect(70, 350, 231, 23))
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.pushButton_cancel = QtWidgets.QPushButton(Dialog)
        self.pushButton_cancel.setGeometry(QtCore.QRect(410, 350, 75, 23))
        self.pushButton_cancel.setObjectName("pushButton_cancel")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 10, 111, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 60, 111, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 110, 111, 21))
        self.label_3.setObjectName("label_3")
        self.lineEdit_warstwa = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_warstwa.setGeometry(QtCore.QRect(140, 10, 321, 20))
        self.lineEdit_warstwa.setObjectName("lineEdit_warstwa")
        self.lineEdit_bazy = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_bazy.setGeometry(QtCore.QRect(140, 60, 321, 20))
        self.lineEdit_bazy.setObjectName("lineEdit_bazy")
        self.comboBox_wlas = QtWidgets.QComboBox(Dialog)
        self.comboBox_wlas.setGeometry(QtCore.QRect(140, 110, 411, 22))
        self.comboBox_wlas.setObjectName("comboBox_wlas")
        self.comboBox_wlas.addItem("")
        self.comboBox_wlas.addItem("")
        self.comboBox_ident = QtWidgets.QComboBox(Dialog)
        self.comboBox_ident.setEnabled(False)
        self.comboBox_ident.setGeometry(QtCore.QRect(140, 170, 411, 22))
        self.comboBox_ident.setObjectName("comboBox_ident")
        self.comboBox_ident.addItem("")
        self.comboBox_ident.addItem("")
        self.comboBox_ident.addItem("")
        self.comboBox_ident.addItem("")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 140, 171, 21))
        self.label_5.setObjectName("label_5")
        self.groupBox_adradm = QtWidgets.QGroupBox(Dialog)
        self.groupBox_adradm.setEnabled(False)
        self.groupBox_adradm.setGeometry(QtCore.QRect(20, 200, 211, 51))
        self.groupBox_adradm.setObjectName("groupBox_adradm")
        self.comboBox_kol_adradm = QtWidgets.QComboBox(self.groupBox_adradm)
        self.comboBox_kol_adradm.setGeometry(QtCore.QRect(20, 20, 171, 22))
        self.comboBox_kol_adradm.setObjectName("comboBox_kol_adradm")
        self.groupBox_kol = QtWidgets.QGroupBox(Dialog)
        self.groupBox_kol.setEnabled(False)
        self.groupBox_kol.setGeometry(QtCore.QRect(240, 200, 301, 141))
        self.groupBox_kol.setObjectName("groupBox_kol")
        self.label_4 = QtWidgets.QLabel(self.groupBox_kol)
        self.label_4.setGeometry(QtCore.QRect(10, 20, 131, 21))
        self.label_4.setObjectName("label_4")
        self.label_6 = QtWidgets.QLabel(self.groupBox_kol)
        self.label_6.setGeometry(QtCore.QRect(10, 50, 151, 21))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.groupBox_kol)
        self.label_7.setGeometry(QtCore.QRect(10, 80, 151, 21))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.groupBox_kol)
        self.label_8.setGeometry(QtCore.QRect(10, 110, 151, 21))
        self.label_8.setObjectName("label_8")
        self.comboBox_kol_gm = QtWidgets.QComboBox(self.groupBox_kol)
        self.comboBox_kol_gm.setGeometry(QtCore.QRect(170, 20, 121, 22))
        self.comboBox_kol_gm.setObjectName("comboBox_kol_gm")
        self.comboBox_kol_obr = QtWidgets.QComboBox(self.groupBox_kol)
        self.comboBox_kol_obr.setGeometry(QtCore.QRect(170, 50, 121, 22))
        self.comboBox_kol_obr.setObjectName("comboBox_kol_obr")
        self.comboBox_kol_nrdz = QtWidgets.QComboBox(self.groupBox_kol)
        self.comboBox_kol_nrdz.setGeometry(QtCore.QRect(170, 80, 121, 22))
        self.comboBox_kol_nrdz.setObjectName("comboBox_kol_nrdz")
        self.comboBox_kol_ark = QtWidgets.QComboBox(self.groupBox_kol)
        self.comboBox_kol_ark.setGeometry(QtCore.QRect(170, 110, 121, 22))
        self.comboBox_kol_ark.setObjectName("comboBox_kol_ark")
        self.pushButton_bazy = QtWidgets.QPushButton(Dialog)
        self.pushButton_bazy.setGeometry(QtCore.QRect(470, 60, 75, 23))
        self.pushButton_bazy.setObjectName("pushButton_bazy")
        self.pushButton_warstwa = QtWidgets.QPushButton(Dialog)
        self.pushButton_warstwa.setGeometry(QtCore.QRect(470, 10, 75, 23))
        self.pushButton_warstwa.setObjectName("pushButton_warstwa")
        self.label_9 = QtWidgets.QLabel(Dialog)
        self.label_9.setGeometry(QtCore.QRect(90, 30, 391, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setItalic(True)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_bazy_wynik = QtWidgets.QLabel(Dialog)
        self.label_bazy_wynik.setGeometry(QtCore.QRect(140, 80, 401, 20))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setItalic(True)
        self.label_bazy_wynik.setFont(font)
        self.label_bazy_wynik.setText("")
        self.label_bazy_wynik.setObjectName("label_bazy_wynik")

        self.retranslateUi(Dialog)
        self.pushButton_cancel.clicked.connect(Dialog.close)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_ok.setText(_translate("Dialog", "OK"))
        self.pushButton_cancel.setText(_translate("Dialog", "Porzuć"))
        self.label.setText(_translate("Dialog", "Warstwa wejściowa:"))
        self.label_2.setText(_translate("Dialog", "Katalog z bazami:"))
        self.label_3.setText(_translate("Dialog", "Własność:"))
        self.comboBox_wlas.setItemText(0, _translate("Dialog", "OF i współwłasności"))
        self.comboBox_wlas.setItemText(1, _translate("Dialog", "Wszystkie"))
        self.comboBox_ident.setItemText(0, _translate("Dialog", "---"))
        self.comboBox_ident.setItemText(1, _translate("Dialog", "Adres administracyjny (200201_5.0010.581/12)"))
        self.comboBox_ident.setItemText(2, _translate("Dialog", "Kolumny z gminą, obrębem, numerem i ew. arkuszem"))
        self.comboBox_ident.setItemText(3, _translate("Dialog", "PARCELID (20020150010.581/12)"))
        self.label_5.setText(_translate("Dialog", "Sposób identyfikacji działek:"))
        self.groupBox_adradm.setTitle(_translate("Dialog", "Kolumna z adresem administracyjnym"))
        self.groupBox_kol.setTitle(_translate("Dialog", "Kolumny z danymi adresowymi"))
        self.label_4.setText(_translate("Dialog", "Kolumna z kodem gminy:"))
        self.label_6.setText(_translate("Dialog", "Kolumna z kodem obrębu:"))
        self.label_7.setText(_translate("Dialog", "Kolumna z numerem działki:"))
        self.label_8.setText(_translate("Dialog", "Kolumna z kodem arkusza:"))
        self.pushButton_bazy.setText(_translate("Dialog", "Wybierz"))
        self.pushButton_warstwa.setText(_translate("Dialog", "Wybierz"))
        self.label_9.setText(_translate("Dialog", "Podaj powyżej albo do analizy pobrana zostanie aktualnie zaznaczona z TOC"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

