# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_wyszukaj_lz.ui'
#
# Created by: PyQt5 UI code generator 5.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(665, 328)
        Dialog.setMinimumSize(QtCore.QSize(665, 248))
        Dialog.setMaximumSize(QtCore.QSize(665, 648))
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(30, 10, 441, 18))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lineEdit_ls = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_ls.setGeometry(QtCore.QRect(10, 30, 551, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lineEdit_ls.setFont(font)
        self.lineEdit_ls.setObjectName("lineEdit_ls")
        self.pushButton_ls = QtWidgets.QPushButton(Dialog)
        self.pushButton_ls.setGeometry(QtCore.QRect(570, 30, 88, 34))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.pushButton_ls.setFont(font)
        self.pushButton_ls.setObjectName("pushButton_ls")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(30, 140, 511, 18))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_oddz = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_oddz.setGeometry(QtCore.QRect(10, 160, 551, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lineEdit_oddz.setFont(font)
        self.lineEdit_oddz.setObjectName("lineEdit_oddz")
        self.pushButton_oddz = QtWidgets.QPushButton(Dialog)
        self.pushButton_oddz.setGeometry(QtCore.QRect(570, 160, 88, 34))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.pushButton_oddz.setFont(font)
        self.pushButton_oddz.setObjectName("pushButton_oddz")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 230, 211, 18))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.lineEdit_odl = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_odl.setGeometry(QtCore.QRect(240, 220, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lineEdit_odl.setFont(font)
        self.lineEdit_odl.setMaxLength(30)
        self.lineEdit_odl.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit_odl.setObjectName("lineEdit_odl")
        self.pushButton_ok = QtWidgets.QPushButton(Dialog)
        self.pushButton_ok.setGeometry(QtCore.QRect(40, 270, 321, 34))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_ok.setFont(font)
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.pushButton_anuluj = QtWidgets.QPushButton(Dialog)
        self.pushButton_anuluj.setGeometry(QtCore.QRect(420, 270, 161, 34))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.pushButton_anuluj.setFont(font)
        self.pushButton_anuluj.setObjectName("pushButton_anuluj")
        self.label_uwagi = QtWidgets.QLabel(Dialog)
        self.label_uwagi.setGeometry(QtCore.QRect(20, 200, 601, 18))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setItalic(True)
        self.label_uwagi.setFont(font)
        self.label_uwagi.setStyleSheet("QLabel { color : rgb(255, 0, 0);}")
        self.label_uwagi.setText("")
        self.label_uwagi.setObjectName("label_uwagi")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(30, 70, 441, 18))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_uz = QtWidgets.QLineEdit(Dialog)
        self.lineEdit_uz.setGeometry(QtCore.QRect(10, 90, 551, 32))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.lineEdit_uz.setFont(font)
        self.lineEdit_uz.setObjectName("lineEdit_uz")
        self.pushButton_uz = QtWidgets.QPushButton(Dialog)
        self.pushButton_uz.setGeometry(QtCore.QRect(570, 90, 88, 34))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.pushButton_uz.setFont(font)
        self.pushButton_uz.setObjectName("pushButton_uz")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Warstwa LS:"))
        self.pushButton_ls.setText(_translate("Dialog", "Wybierz"))
        self.label_2.setText(_translate("Dialog", "Warstwa ODDZ z PGL LP (przycięta do obiektu):"))
        self.pushButton_oddz.setText(_translate("Dialog", "Wybierz"))
        self.label_3.setText(_translate("Dialog", "Odległość do innego LSa:  [m]"))
        self.lineEdit_odl.setText(_translate("Dialog", "15"))
        self.pushButton_ok.setText(_translate("Dialog", "OK"))
        self.pushButton_anuluj.setText(_translate("Dialog", "Anuluj"))
        self.label_4.setText(_translate("Dialog", "Warstwa użytków:"))
        self.pushButton_uz.setText(_translate("Dialog", "Wybierz"))


