# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LasR
                                 A QGIS plugin
 Plugin do automatyzacji pracy przy Uproszczonych Planach Urządzania Lasu
 (mdb + shp).
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2018-07-16
        git sha              : $Format:%H$
        copyright            : (C) 2020 by Paweł Krąpiec
        email                : p.krapiec@lasr.pl
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from PyQt5.QtCore import QSettings, QTranslator, qVersion, QCoreApplication, Qt
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QAction, QMenu

# Initialize Qt resources from file resources.py
# from .resources import *
# Import the code for the dialog
# from .las_r_dialog import LasRDialog
import os.path
from qgis.core import QgsProject
from qgis.utils import plugins

from .skrypty import sprawdz_dzkat, shp_dopOddzWydz, sprawdzenia_topo, \
    baza_dopisz_fochr, shp_dopisz_kody,  shp_symbolizacja, shp_adr_les, \
    shp_literkuj, shp_numeruj, shp_sprWydzOddz, shp_przygCiecie, \
    spr_wydzielen, shp_wyszukaj_lz, naklejki, sprawdz_ls, shp_eksport_kml, \
    baza_rozlicz_pow_wydz, baza_sprawdz_rozl, funkcje, shp_spr_wlasn_wydz, \
    baza_dopisz_wydz, baza_przeliterkuj, baza_dopisz_pnsw, baza_klonuj_wydz, \
    shp_atlasuj, baza_usun_op, baza_zabiegi, shp_dociagnij_poly, raport_wyles,\
    baza_kontrola_ls, baza_anonimizuj, baza_polacz, shp_sprawdz_ciecie, \
    baza_napraw_stor_spec, shp_polacz_teren, shp_czysc_kol, raport_wyciagi, \
    shp_konwertuj, shp_uzup_adradm

from .skrypty.zabiegi.main import Zabiegi


class LasR:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'LasR_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)

            if qVersion() > '4.3.3':
                QCoreApplication.installTranslator(self.translator)

        # Create the dialog (after translation) and keep reference
        # self.dlg = LasRDialog()

        # Declare instance attributes
        # self.actions = []
        # self.menu = self.tr(u'&Las-R')
        # # TODO: We are going to let the user set this up in a future iteratio
        self.toolbar = self.iface.addToolBar(u'LAS-R')
        self.toolbar.setObjectName(u'LasR')

        self.toolbar_skr = self.iface.addToolBar(u'LAS-R skróty')
        self.toolbar_skr.setObjectName(u'LasR_skrrroty')

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('LasR', message)

    def add_action(
            self,
            icon_path,
            text,
            callback,
            enabled_flag=True,
            add_to_menu=True,
            add_to_toolbar=True,
            status_tip=None,
            whats_this=None,
            parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        # akcje toolbara --------------------
        self.akcje_toolbara = []
        # koniec akcji ----------------------

        # ikony -----------------------------
        ico_wydz_dopisz = QIcon(
            os.path.join(self.plugin_dir, 'ico', 'wydz_dopisz.png'))
        ico_wydz_rys_zab = QIcon(
            os.path.join(self.plugin_dir, 'ico', 'wydz_rys_zab.png'))
        ico_wydz_rys_gat = QIcon(
            os.path.join(self.plugin_dir, 'ico', 'wydz_rys_gat.png'))
        ico_wydz_rys_orto = QIcon(
            os.path.join(self.plugin_dir, 'ico', 'wydz_rys_orto.png'))
        ico_wydz_rys_stl = QIcon(
            os.path.join(self.plugin_dir, 'ico', 'wydz_rys_stl.png'))
        ico_topo = QIcon(
            os.path.join(self.plugin_dir, 'ico', 'spr_topo.png'))
        ico_wydz_spr = QIcon(
            os.path.join(self.plugin_dir, 'ico', 'wydz_sprawdz.png'))
        ico_utf8 = QIcon(
            os.path.join(self.plugin_dir, 'ico', 'utf-8.png'))
        ico_desel_all = QIcon(
            os.path.join(self.plugin_dir, 'ico', 'deselect_all.png'))
        ico_check = QIcon(os.path.join(
            self.plugin_dir, 'ico', 'check_geom.png'))
        ico_pow_graf = QIcon(
            os.path.join(self.plugin_dir, 'ico', 'pow_graf.png'))
        ico_dzkat = QIcon(
            os.path.join(self.plugin_dir, 'ico', 'dzkat.png'))
        ico_klu = QIcon(
            os.path.join(self.plugin_dir, 'ico', 'klu.png'))
        ico_wezelki = QIcon(
            os.path.join(self.plugin_dir, 'ico', 'wezelki.png'))
        ico_gen_pola = QIcon(
            os.path.join(self.plugin_dir, 'ico', 'genPola.png'))
        ico_num_pola = QIcon(
            os.path.join(self.plugin_dir, 'ico', 'numPola.png'))
        ico_pok_lay = QIcon(
            os.path.join(self.plugin_dir, 'ico', 'pokazLay.png'))
        # koniec ikon -----------------------

        self.menu = QMenu(self.iface.mainWindow())
        self.menu.setObjectName('LAS-R')
        self.menu.setTitle('LAS-R')

        menuBar = self.iface.mainWindow().menuBar()
        menuBar.insertMenu(self.iface.firstRightStandardMenu().menuAction(),
                           self.menu)

        self.m_przyg_danych = QMenu('Przygotowanie danych', self.menu)
        self.m_rozlicz_pow = QMenu('Rozliczenie powierzchni', self.menu)
        self.m_kontrola_danych = QMenu('Kontrola danych', self.menu)
        self.m_style = QMenu('Style warstw', self.menu)
        self.m_narzedzia = QMenu('Narzędziowe', self.menu)
        self.m_raporty = QMenu('Raporty', self.menu)

        self.menu.addMenu(self.m_przyg_danych)
        self.menu.addMenu(self.m_rozlicz_pow)
        self.menu.addMenu(self.m_kontrola_danych)
        self.menu.addMenu(self.m_style)
        self.menu.addMenu(self.m_narzedzia)
        self.menu.addMenu(self.m_raporty)

        self.przyg_dzewid = QAction(QIcon(None),
                                    u"Przygotuj działki ewidencyjne",
                                    self.iface.mainWindow())
        self.m_przyg_danych.addAction(self.przyg_dzewid)
        self.przyg_dzewid.triggered.connect(self.przygotuj_dzewid)

        self.przyg_ls = QAction(
            QIcon(None), u"Przygotuj Lsy", self.iface.mainWindow())
        self.m_przyg_danych.addAction(self.przyg_ls)
        self.przyg_ls.triggered.connect(self.przygotuj_ls)

        self.a_snapuj = QAction(QIcon(None),
                                "Przysnapuj do dzałek",
                                self.iface.mainWindow())
        self.m_przyg_danych.addAction(self.a_snapuj)
        self.a_snapuj.triggered.connect(self.przysnapuj_do_dzewid)

        self.przyg_teren = QAction(
            QIcon(None), 'Przygotuj w teren', self.iface.mainWindow())
        self.m_przyg_danych.addAction(self.przyg_teren)
        self.przyg_teren.triggered.connect(self.przygotuj_do_terenu)

        self.m_przyg_danych.addSeparator()

        self.wyz_lz = QAction(QIcon(None),
                              'LZ - wyznacz potencjalne',
                              self.iface.mainWindow())
        self.m_przyg_danych.addAction(self.wyz_lz)
        self.wyz_lz.triggered.connect(self.wyszukaj_lz)

        self.kas_op = QAction(QIcon(None),
                              "Kasuj OP",
                              self.iface.mainWindow())
        self.m_przyg_danych.addAction(self.kas_op)

        self.kas_op.triggered.connect(self.kasuj_wlas_OP)

        self.eksp_kml = QAction(QIcon(None),
                                u"Wyeksportuj do KML",
                                self.iface.mainWindow())
        self.m_przyg_danych.addAction(self.eksp_kml)
        self.eksp_kml.triggered.connect(self.eksportuj_do_KML)

        # -----------------------------------------

        self.przyg_ciec = QAction(
            QIcon(None), 'Przygotuj wydzielenia do cięcia',
            self.iface.mainWindow())
        self.m_rozlicz_pow.addAction(self.przyg_ciec)
        self.przyg_ciec.triggered.connect(self.przygotuj_do_ciecia)

        self.lacz_karty = QAction(
            QIcon(None), 'Połącz pomiary od taksatorów',
            self.iface.mainWindow())
        self.m_rozlicz_pow.addAction(self.lacz_karty)
        self.lacz_karty.triggered.connect(self.polacz_pliki_teren)

        self.przyg_klep = QAction(
            QIcon(None), 'Sprawdź karty w wydzieleniach',
            self.iface.mainWindow())
        self.m_rozlicz_pow.addAction(self.przyg_klep)
        self.przyg_klep.triggered.connect(self.sprawdzenie_ciecia)

        self.zanum = QAction(
            QIcon(None), 'Zanumeruj oddziały', self.iface.mainWindow())
        self.m_rozlicz_pow.addAction(self.zanum)
        self.zanum.triggered.connect(self.zanumeruj)

        self.dop_w_o = QAction(
            QIcon(None), 'Dopisz oddziały do wydzieleń',
            self.iface.mainWindow())
        self.m_rozlicz_pow.addAction(self.dop_w_o)
        self.dop_w_o.triggered.connect(self.dopisz_wydz_w_oddz)

        self.zalit = QAction(
            QIcon(None), 'Zaliterkuj wydzielenia', self.iface.mainWindow())
        self.m_rozlicz_pow.addAction(self.zalit)
        self.zalit.triggered.connect(self.zaliterkuj)

        self.dop_adrles = QAction(
            QIcon(None), 'Zaadresuj [ADR_LES]', self.iface.mainWindow())
        self.m_rozlicz_pow.addAction(self.dop_adrles)
        self.dop_adrles.triggered.connect(self.dopisz_adrles)

        self.dopisz_wydz = QAction(QIcon(None),
                                   'Dopisz/uzupełnij wydzielenia w bazie',
                                   self.iface.mainWindow())
        self.m_rozlicz_pow.addAction(self.dopisz_wydz)
        self.dopisz_wydz.triggered.connect(self.dopisz_wydzielenia)

        self.rozlicz_wydz = QAction(QIcon(None),
                                    'Rozlicz powierzchnię wydz.',
                                    self.iface.mainWindow())
        self.m_rozlicz_pow.addAction(self.rozlicz_wydz)
        self.rozlicz_wydz.triggered.connect(self.rozlicz_pow_wydzielen)

        self.dop_pnsw = QAction(
            QIcon(None), 'Dopisz/uzupełnij PNSW',
            self.iface.mainWindow())
        self.m_rozlicz_pow.addAction(self.dop_pnsw)
        self.dop_pnsw.triggered.connect(self.dopisz_pnsw)

        self.przyg_rap = QAction(
            QIcon(None), 'Stwórz raport kart do klepania',
            self.iface.mainWindow())
        self.m_rozlicz_pow.addAction(self.przyg_rap)
        self.przyg_rap.triggered.connect(self.raport_kart_ciecia)

        self.dop_zab = QAction(
            QIcon(None), 'Zabiegi dopisz/sprawdź (stare)',
            self.iface.mainWindow())
        self.m_rozlicz_pow.addAction(self.dop_zab)
        self.dop_zab.triggered.connect(self.zabiegi)

        self.dop_zab_nowe = QAction(
            QIcon(None), 'Zabiegi dopisz/sprawdź (nowe)',
            self.iface.mainWindow())
        self.m_rozlicz_pow.addAction(self.dop_zab_nowe)
        self.dop_zab_nowe.triggered.connect(self.zabiegi_nowe)

        self.m_rozlicz_pow.addSeparator()

        self.dop_fo = QAction(
            QIcon(None), 'Dopisz formy ochrony', self.iface.mainWindow())
        self.m_rozlicz_pow.addAction(self.dop_fo)
        self.dop_fo.triggered.connect(self.dopisz_f_ochr)

        self.przelit = QAction(
            QIcon(None), 'Przeliterkuj (Całość)', self.iface.mainWindow())
        self.m_rozlicz_pow.addAction(self.przelit)
        self.przelit.triggered.connect(self.przeliterkuj)

        self.klon = QAction(
            QIcon(None), 'Klonuj wydzielenia w bazie', self.iface.mainWindow())
        self.m_rozlicz_pow.addAction(self.klon)
        self.klon.triggered.connect(self.klonuj)

        # ----------------------------------------

        self.spr_odl_wydz = QAction(QIcon(None),
                                    'Sprawdź odległości w wydzieleniach',
                                    self.iface.mainWindow())
        self.m_kontrola_danych.addAction(self.spr_odl_wydz)
        self.spr_odl_wydz.triggered.connect(self.sprawdzenie_odl_w_wydz)

        self.spr_wl_wydz = QAction(QIcon(None),
                                   'Sprawdź własności w wydzieleniach',
                                   self.iface.mainWindow())
        self.m_kontrola_danych.addAction(self.spr_wl_wydz)
        self.spr_wl_wydz.triggered.connect(self.sprawdzenie_wlasnosci_wydz)

        self.spr_w_o = QAction(QIcon(None),
                               'Sprawdź wydzielenia w oddziałach',
                               self.iface.mainWindow())
        self.m_kontrola_danych.addAction(self.spr_w_o)
        self.spr_w_o.triggered.connect(self.sprawdz_wydz_w_oddz)

        self.spr_kontr_ls = QAction(
            QIcon(None),
            'Kontrola Ls z bazą',
            self.iface.mainWindow())
        self.m_kontrola_danych.addAction(self.spr_kontr_ls)
        self.spr_kontr_ls.triggered.connect(self.kontrola_ls_z_baza)

        self.spr_rozlicz_wydz = QAction(
            QIcon(None),
            'Sprawdz rozliczenie powierzchni wydz.',
            self.iface.mainWindow())
        self.m_kontrola_danych.addAction(self.spr_rozlicz_wydz)
        self.spr_rozlicz_wydz.triggered.connect(self.sprawdz_pow_wydzielen)

        self.spr_wydz = QAction(
            ico_wydz_spr, 'Sprawdź wydzielenia', self.iface.mainWindow())
        self.m_kontrola_danych.addAction(self.spr_wydz)
        self.spr_wydz.triggered.connect(self.sprawdzenie_wydzielen)

        self.spr_topo = QAction(
            ico_topo, 'Sprawdź topologię', self.iface.mainWindow())
        self.m_kontrola_danych.addAction(self.spr_topo)
        self.spr_topo.triggered.connect(self.sprawdz_topologie)

        # ------------------------------------

        self.menu.addSeparator()

        self.dop_wydz = QAction(ico_wydz_dopisz,
                                'Dopisz atrybuty do wydzieleń',
                                self.iface.mainWindow())
        self.menu.addAction(self.dop_wydz)
        self.dop_wydz.triggered.connect(self.dopisanie_wydzielen)

        self.nakl = QAction(QIcon(None),
                            'Generuj naklejki',
                            self.iface.mainWindow())
        self.menu.addAction(self.nakl)
        self.nakl.triggered.connect(self.rysuj_naklejki)

        # -------------------------------------

        self.rys_gat = QAction(ico_wydz_rys_gat,
                               'Rysuj gatunki',
                               self.iface.mainWindow())
        self.m_style.addAction(self.rys_gat)
        self.rys_gat.triggered.connect(self.rysuj_gatunki)

        self.rys_zab = QAction(ico_wydz_rys_zab,
                               'Rysuj zabiegi',
                               self.iface.mainWindow())
        self.m_style.addAction(self.rys_zab)
        self.rys_zab.triggered.connect(self.rysuj_zabiegi)

        self.rys_stl = QAction(ico_wydz_rys_stl,
                               'Rysuj STL',
                               self.iface.mainWindow())
        self.m_style.addAction(self.rys_stl)
        self.rys_stl.triggered.connect(self.rysuj_stl)

        self.rys_orto = QAction(ico_wydz_rys_orto,
                                'Rysuj na orto',
                                self.iface.mainWindow())
        self.m_style.addAction(self.rys_orto)
        self.rys_orto.triggered.connect(self.rysuj_orto)

        self.rys_dz = QAction(ico_dzkat,
                              'Rysuj Działki',
                              self.iface.mainWindow())
        self.m_style.addAction(self.rys_dz)
        self.rys_dz.triggered.connect(self.rysuj_dzkat)

        self.rys_klu = QAction(ico_klu,
                               'Rysuj KLU',
                               self.iface.mainWindow())
        self.m_style.addAction(self.rys_klu)
        self.rys_klu.triggered.connect(self.rysuj_klu)

        self.a_dod_adm = QAction(
            QIcon(None), 'Dodaj [MUNICIP, COMUNITY]', self.iface.mainWindow())
        self.m_narzedzia.addAction(self.a_dod_adm)
        self.a_dod_adm.triggered.connect(self.dodaj_mun_comm)

        self.a_dop_adm = QAction(
            QIcon(None),
            'Uzupełnij [MUNICIP, COMMUNITY]',
            self.iface.mainWindow())
        self.m_narzedzia.addAction(self.a_dop_adm)
        self.a_dop_adm.triggered.connect(self.dopisz_adradm)

        self.a_czy_kol = QAction(
            QIcon(None), 'Usuń zawartość kolumn', self.iface.mainWindow())
        self.m_narzedzia.addAction(self.a_czy_kol)
        self.a_czy_kol.triggered.connect(self.przeczysc_kolumny)

        self.a_anon = QAction(QIcon(None),
                              "Anonimizuj bazy TPU",
                              self.iface.mainWindow())
        self.m_narzedzia.addAction(self.a_anon)
        self.a_anon.triggered.connect(self.anonimizuj)

        self.a_fstspec = QAction(QIcon(None),
                                 "Napraw F_STOREY_SPECIES",
                                 self.iface.mainWindow())
        self.m_narzedzia.addAction(self.a_fstspec)
        self.a_fstspec.triggered.connect(self.napraw_f_stor_spec)

        self.a_reproj = QAction(
            QIcon(None), "Reprojekcja warstw", self.iface.mainWindow())
        self.m_narzedzia.addAction(self.a_reproj)
        self.a_reproj.triggered.connect(self.reprojekcja_warstw)

        self.a_copy = QAction(QIcon(None),
                              "Połącz bazy TPU",
                              self.iface.mainWindow())
        self.m_narzedzia.addAction(self.a_copy)
        self.a_copy.triggered.connect(self.lacz_bazy)

        self.a_rap_wyles = QAction(
            QIcon(None), 'Karty wylesień na dz.', self.iface.mainWindow())
        self.m_raporty.addAction(self.a_rap_wyles)
        self.a_rap_wyles.triggered.connect(self.generuj_karty_wylesien)

        self.a_wyciagi = QAction(
            QIcon(None), 'Wyciagi dla właścicieli', self.iface.mainWindow())
        self.m_raporty.addAction(self.a_wyciagi)
        self.a_wyciagi.triggered.connect(self.generuj_wyciagi)

        # toolbar -----------------------------
        self.dop_meta = QAction(ico_wydz_dopisz,
                                'Dopisz metadane',
                                self.iface.mainWindow())
        self.toolbar.addAction(self.dop_meta)
        self.dop_meta.triggered.connect(self.dopisanie_wydzielen)

        self.toolbar.addAction(self.spr_wydz)

        self.toolbar.addSeparator()

        self.toolbar.addAction(self.rys_gat)
        self.toolbar.addAction(self.rys_stl)
        self.toolbar.addAction(self.rys_dz)
        self.toolbar.addAction(self.rys_klu)

        self.rys_wez = QAction(ico_wezelki,
                               'Pokaż węzełki',
                               self.iface.mainWindow())
        self.m_style.addAction(self.rys_wez)
        self.toolbar.addAction(self.rys_wez)
        self.rys_wez.triggered.connect(self.rysuj_wezelki)

        self.a_pokaz_lay = QAction(ico_pok_lay,
                                   'Pokaż Layout',
                                   self.iface.mainWindow())
        self.a_pokaz_lay.triggered.connect(self.pokaz_layout)
        self.toolbar.addAction(self.a_pokaz_lay)

        self.toolbar.addSeparator()

        self.rys_atl = QAction(ico_gen_pola,
                               'Rysuj pola atlasowe',
                               self.iface.mainWindow())
        self.toolbar.addAction(self.rys_atl)
        self.rys_atl.triggered.connect(self.rysuj_atlas)

        self.num_atl = QAction(ico_num_pola,
                               'Numeruj pola atlasu',
                               self.iface.mainWindow())
        self.toolbar.addAction(self.num_atl)
        self.num_atl.triggered.connect(self.numeruj_atlas)

        self.toolbar.addSeparator()

        self.toolbar.addAction(self.spr_topo)
        self.akcje_toolbara = [self.dop_meta,
                               self.spr_wydz,
                               self.rys_dz,
                               self.rys_klu,
                               self.rys_gat,
                               self.rys_wez,
                               self.rys_atl,
                               self.spr_topo,
                               self.a_pokaz_lay,
                               ]
        # toolbar koniec ---------------------

        # toolbar ze skrotami -----------------------
        self.spr_geom = QAction(ico_check,
                                'Sprawdź geometrię',
                                self.iface.mainWindow())
        self.toolbar_skr.addAction(self.spr_geom)
        self.spr_geom.triggered.connect(self.sprawdz_geom)

        self.uutf8 = QAction(ico_utf8,
                             'ustaw kodowanie UTF-8',
                             self.iface.mainWindow())
        self.toolbar_skr.addAction(self.uutf8)
        self.uutf8.triggered.connect(self.ustaw_utf8)

        self.toolbar_skr.addAction(self.iface.actionSplitFeatures())

        if 'DigitizingTools' in plugins:
            ico_split = QIcon(":/MultiToSingle.png")
            self.msplit = QAction(ico_split,
                                  'Rozbij multipoligony',
                                  self.iface.mainWindow())
            self.toolbar_skr.addAction(self.msplit)
            self.msplit.triggered.connect(self.multipart_split)

        self.toolbar_skr.addAction(self.iface.actionAddRing())
        self.toolbar_skr.addAction(self.iface.actionAddFeature())
        self.toolbar_skr.addAction(self.iface.actionSelectRectangle())
        self.odzn = QAction(ico_desel_all,
                            'Unselect All',
                            self.iface.mainWindow())
        self.toolbar_skr.addAction(self.odzn)
        self.odzn.triggered.connect(self.odznacz)

        self.toolbar_skr.addAction(self.iface.actionVertexTool())

        self.pg = QAction(ico_pow_graf,
                          'oblicz powierzchnię graficzną',
                          self.iface.mainWindow())
        self.toolbar_skr.addAction(self.pg)
        self.pg.triggered.connect(self.powierzchnia_graf)

        self.akcje_toolbar_skr = [
            self.spr_geom,
            self.uutf8,
            self.iface.actionSplitFeatures(),
            self.msplit,
            self.odzn,
            self.pg,
            self.iface.actionAddRing(),
            self.iface.actionAddFeature(),
            self.iface.actionSelectRectangle(),
            self.iface.actionVertexTool(),
        ]
        # self.menu.addSeparator()
        # icon_path = ':/plugins/las_r/icon.png'
        # self.add_action(
        #     icon_path,
        #     text=self.tr(u'Las-R'),
        #     callback=self.run,
        #     parent=self.iface.mainWindow())

        self.dockWidget = baza_klonuj_wydz.PobierzDaneDock(self.iface)
        self.iface.addDockWidget(Qt.RightDockWidgetArea, self.dockWidget)
        self.dockWidget.hide()

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        # for action in self.actions:
        #     self.iface.removePluginMenu(
        #         self.tr(u'&Las-R'),
        #         action)
        #     self.iface.removeToolBarIcon(action)
        # remove the toolbar
        if self.menu is not None:
            self.iface.mainWindow().menuBar().removeAction(
                self.menu.menuAction())
        for a in self.akcje_toolbara:
            self.iface.removeToolBarIcon(a)
        # del self.toolbar
        self.toolbar.clear()
        self.toolbar.deleteLater()

        for a in self.akcje_toolbar_skr:
            self.iface.removeToolBarIcon(a)
        # del self.toolbar_skr
        self.toolbar_skr.clear()
        self.toolbar_skr.deleteLater()
        self.dockWidget.close()
        self.iface.removeDockWidget(self.dockWidget)

    def run(self):
        """Run method that performs all the real work"""
        # show the dialog
        # self.dlg.show()
        # Run the dialog event loop
        # result = self.dlg.exec_()
        # See if OK was pressed
        # if result:
        #    Do something useful here - delete the line containing pass and
        #    substitute with your code.
        #    pass
        pass

    def przygotuj_dzewid(self):
        sprawdz_dzkat.SprawdzDzKat(self.iface)

    def przygotuj_ls(self):
        spr = sprawdz_ls.SprawdzLs(self.iface)
        if not spr.sprawdz_warstwy():
            return
        if not spr.wczytaj():
            return
        if not spr.sprawdz():
            return
        if spr.przygotuj():
            spr.przetworz()

    def dopisz_f_ochr(self):
        b = baza_dopisz_fochr.DopiszFO(self.iface)
        if not b.pobierz_dane_od_uzytkownika():
            return
        if not b.poprawne_wydz():
            return False
        if not b.poprawne_fo():
            return False
        if b.wybierz_fo():
            b.wybierz_wydz()
            b.dopisz_do_bazy()

    def kasuj_wlas_OP(self):
        baza_usun_op.UsunOP(self.iface)

    def anonimizuj(self):
        baza_anonimizuj.Anonimizuj(self.iface)

    def dopisz_wydzielenia(self):
        w = baza_dopisz_wydz.DopiszWydzielenia(self.iface)
        if w.sprawdz_dane():
            w.wczytaj_wydz_shp()
            w.wczytaj_wydz_baza()
            w.dopisz_wydz()
            w.wyswietl_info()

    def rozlicz_pow_wydzielen(self):
        b = baza_rozlicz_pow_wydz.RozliczPowierzchnieWydz(self.iface)
        if not b.sprawdz_dane():
            return
        b.przetnij_wydz_ls()
        if b.zbuduj_strukture():
            b.sprawdz_rozlicz_graf()
            b.zestaw_rozliczenie()
            # b.zapisz_rozliczenie()  # wypisz do csv do sprawdzenia
            if not b.dopisz_rozliczenie():
                return
            else:
                b.sprawdz_rozlicz_rej()
            b.skasuj_robocze()
            b.zapisz_raport()

    def sprawdz_pow_wydzielen(self):
        baza_sprawdz_rozl.sprawdz_rozliczenie_bazy(self.iface)

    def rysuj_atlas(self):
        g = shp_atlasuj.GenerujAtlas(self.iface)
        if not g.wybierz_warstwe():
            return
        if g.pobierz_dane():
            g.stworz_warstwy()
            g.generuj_pola()
            g.zapisz_warstwy()

    def numeruj_atlas(self):
        n = shp_atlasuj.Zanumeruj(self.iface)
        if not n.wczytaj_warstwy():
            return
        if not n.sprawdz_warstwy():
            return
        if n.poprawnie_rozlozone():
            n.zanumeruj_pola()
            n.wyswietl_info()

    def sprawdz_topologie(self):
        b = sprawdzenia_topo.SprawdzTopo(self.iface)
        b.pobierz_feat()
        b.spr_wstepne()
        b.spr_styki()
        b.spr_wasy()
        b.spr_nakladanie()
        b.dodaj_warstwy()

    def sprawdzenie_wydzielen(self):
        k = spr_wydzielen.KontrolaWydzielen(self.iface)
        if not k.wczytaj_baze():
            return
        if k.podst_spr():
            k.kontrola_odl()
            try:
                k.kontrola_powierzchni()
            except Exception:
                pass
            k.spr_oddz()
            k.spr_pnsw()
            k.spr_line()
        k.zapisz_raport()

    def sprawdzenie_odl_w_wydz(self):
        k = spr_wydzielen.KontrolaWydzielen(self.iface)
        if k.wczytaj_wydz():
            k.kontrola_odl()
            k.zapisz_raport('raport_odl_w_wydz')

    def sprawdzenie_wlasnosci_wydz(self):
        w = shp_spr_wlasn_wydz.SprawdzWlasnosciWydzielen(self.iface)
        if w.pobierz_warstwy():
            w.sprawdz_wlasnosci()
            w.wyswietl_info()

    def zabiegi(self):
        z = baza_zabiegi.Zabiegi(self.iface)
        if z.pobierz_dane():
            z.przetworz()
            z.generuj_raport()
            z.wyswietl_info()

    def zabiegi_nowe(self):
        z = Zabiegi()
        if z.pobierz_dane():
            z.przetworz()
            z.generuj_raport()
            z.wyswietl_info()

    def dopisanie_wydzielen(self):
        d = shp_dopisz_kody.DopiszKody(self.iface)
        if d.pobierz_dane():
            if d.poprawne_wydz():
                if d.pobierzBaze():
                    d.dopisz_kody()

    def dopisz_adrles(self):
        shp_adr_les.Zaadresuj(self.iface)

    def dopisz_wydz_w_oddz(self):
        shp_dopOddzWydz.dopOddzWydz(self.iface)

    def przygotuj_do_ciecia(self):
        shp_przygCiecie.przygotuj_wydz_do_ciecia(self.iface)

    def przygotuj_do_terenu(self):
        shp_przygCiecie.przygotuj_do_terenu(self.iface)

    def zaliterkuj(self):
        shp_literkuj.Literkuj(self.iface)

    def przeliterkuj(self):
        p = baza_przeliterkuj.Przeliterkuj(self.iface)
        if not p.sprawdz_warstwe():
            return
        if not p.dopisz_oddzialy():
            return
        p.przygotuj_literkacje()
        p.zaliterkuj()
        p.wygeneruj_adrles()
        p.dopisz_do_bazy()
        p.wyswietl_info()

    def dopisz_pnsw(self):
        p = baza_dopisz_pnsw.DopiszPnsw(self.iface)
        if not p.wczytaj_dane():
            return
        if not p.sprawdz_pnsw():
            return
        p.przygotuj_wpis()
        p.dopisz_do_bazy()
        p.wyswietl_info()

    def klonuj(self):
        self.dockWidget.show()
        # b = baza_klonuj_wydz.Klonuj(self.iface)
        # if b.pobierz_dane():
        #     if b.sprawdz_dane():
        #         b.klonuj()
        #         b.wyswietl_info()

    def zanumeruj(self):
        shp_numeruj.Numeruj(self.iface)

    def sprawdz_wydz_w_oddz(self):
        shp_sprWydzOddz.spr_wydz_oddz(self.iface)

    def eksportuj_do_KML(self):
        s = shp_eksport_kml.EksportujKML(self.iface)
        if s.pobierzDane():
            s.przetworz()
            s.zapisz_kml()

    def lacz_bazy(self):
        p = baza_polacz.PolaczBazy(self.iface)
        if p.pobierz_katalog():
            if p.stworz_docelowa():
                p.kopiuj()
                # try:
                #     p.kopiuj()
                # except Exception:
                #     self.iface.messageBar().clearWidgets()
                #     self.iface.messageBar().pushMessage(
                #         'Błąd', 'Coś się wysypało - krytycznie',
                #         Qgis.Critical, 0)

    def kontrola_ls_z_baza(self):
        k = baza_kontrola_ls.KontrolaLs(self.iface)
        if k.dane_wejsciowe():
            k.przetworz_dane()
            k.zestawienia()
            k.generuj_raport()

    def wyszukaj_lz(self):
        lz = shp_wyszukaj_lz.WyszukajLz(self.iface)
        if lz.pobierz_dane():
            lz.zabuduj_strukt()
            lz.wybierz_potencjalne_lz()
            lz.stworz_warstwe_lz()

    def rysuj_naklejki(self):
        n = naklejki.GenerujNaklejki(self.iface)

        # jeżeli w projekcie sa inne layout i uzytkownik nie chce kontynuowac
        # to przerywamy procedure
        if n.inne_layouty():
            return

        if n.pobierz_dane():
            n.generuj_all()

    def generuj_karty_wylesien(self):
        r = raport_wyles.RaportWylesien(self.iface)
        if r.sprawdz_dane():
            r.generuj_karty()
        del r

    def rysuj_gatunki(self):
        shp_symbolizacja.rysuj(self.iface, 'gat')

    def rysuj_zabiegi(self):
        shp_symbolizacja.rysuj(self.iface, 'zab')

    def rysuj_orto(self):
        shp_symbolizacja.rysuj(self.iface, 'orto')

    def rysuj_stl(self):
        shp_symbolizacja.rysuj(self.iface, 'stl')

    def rysuj_dzkat(self):
        shp_symbolizacja.rysuj(self.iface, 'dzkat')

    def rysuj_klu(self):
        shp_symbolizacja.rysuj(self.iface, 'ls')

    def rysuj_wezelki(self):
        shp_symbolizacja.PokazWezly(self.iface)

    def ustaw_utf8(self):
        funkcje.ustaw_utf8(self.iface)

    def multipart_split(self):
        plugins['DigitizingTools'].multiPartSplitter.process()

    def odznacz(self):
        for key, lyr in QgsProject.instance().mapLayers().items():
            lyr.removeSelection()

    def sprawdz_geom(self):
        m = self.iface.vectorMenu()
        menus = [x for x in m.children() if isinstance(x, QMenu)]
        gmenu = [x for x in menus if x.title() == 'G&eometry Tools'][0]
        y = [x for x in gmenu.actions() if "Check Validity" in x.text()][0]
        y.trigger()

    def powierzchnia_graf(self):
        funkcje.oblicz_pow_graf(self.iface)

    def dodaj_mun_comm(self):
        funkcje.dodaj_adm(self.iface)

    def przysnapuj_do_dzewid(self):
        s = shp_dociagnij_poly.Przyciagnij(self.iface)
        if not s.pobierz_dane():
            return
        if not s.sprawdz_dane():
            return False
        s._przetworz()
        s.podociagaj()
        s.stworz_poligony()
        s.pokaz_warstwy()

    def sprawdzenie_ciecia(self):
        sp = shp_sprawdz_ciecie.SprawdzCiecie(self.iface)
        if not sp.zalozenia_poczatkowe():
            return False
        if not sp.zbuduj_strukture():
            return
        sp.przetworz()
        sp.raport_rozbieznosci()

    def raport_kart_ciecia(self):
        sp = shp_sprawdz_ciecie.SprawdzCiecie(self.iface)
        if not sp.zalozenia_poczatkowe():
            return False
        sp.zbuduj_strukture()
        sp.przetworz()
        sp.raport_spis_kart()

    def pokaz_layout(self):
        funkcje.otworz_kompozycje(self.iface)

    def napraw_f_stor_spec(self):
        np = baza_napraw_stor_spec.WrapNaprawFStorSpec(self.iface)
        if not np.pobierz_sciezke():
            return
        if not np.pobierz_z_bazy():
            self.iface.messageBar().pushCritical(
                'BAZA', 'Nie udało się połączyć z bazą')
        np.zbuduj_strukture()
        np.popraw()
        np.dopisz_poprawki()
        np.raport()
        np.pokaz_wyniki()

    def polacz_pliki_teren(self):
        shp_polacz_teren.polacz_warstwy(self.iface)

    def przeczysc_kolumny(self):
        shp_czysc_kol.czysc_kolumny(self.iface)

    def generuj_wyciagi(self):
        g = raport_wyciagi.GenerujWyciagi(self.iface)
        g.generowanie()

    def reprojekcja_warstw(self):
        rep = shp_konwertuj.KonwertujWarstwy()
        rep.ustaw_dialog()
        rep.show()

    def dopisz_adradm(self):
        shp_uzup_adradm.DopiszAdres()
