# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LasR
                                 A QGIS plugin
 Plugin do automatyzacji pracy przy Uproszczonych Planach Urządzania Lasu
 (mdb + shp).
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2018-07-16
        git sha              : $Format:%H$
        copyright            : (C) 2018 by Paweł Krąpiec
        email                : p.krapiec@lasr.pl
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from PyQt5.QtCore import QSettings, QTranslator, qVersion, QCoreApplication
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QAction, QMenu

# Initialize Qt resources from file resources.py
# from .resources import *
# Import the code for the dialog
# from .las_r_dialog import LasRDialog
import os.path

from .skrypty import sprawdz_dzkat, shp_dopOddzWydz, sprawdzenia_topo, \
    baza_dopisz_fochr, shp_dopisz_kody,  shp_symbolizacja, shp_adr_les, \
    shp_literkuj, shp_numeruj, shp_sprWydzOddz, shp_przygCiecie, \
    spr_wydzielen, shp_wyszukaj_lz, naklejki, sprawdz_ls, shp_eksport_kml, \
    baza_rozlicz_pow_wydz


class LasR:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'LasR_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)

            if qVersion() > '4.3.3':
                QCoreApplication.installTranslator(self.translator)

        # Create the dialog (after translation) and keep reference
        # self.dlg = LasRDialog()

        # Declare instance attributes
        # self.actions = []
        # self.menu = self.tr(u'&Las-R')
        # # TODO: We are going to let the user set this up in a future iteratio
        self.toolbar = self.iface.addToolBar(u'LAS-R')
        self.toolbar.setObjectName(u'LasR')

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('LasR', message)

    def add_action(
            self,
            icon_path,
            text,
            callback,
            enabled_flag=True,
            add_to_menu=True,
            add_to_toolbar=True,
            status_tip=None,
            whats_this=None,
            parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            self.toolbar.addAction(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        # akcje toolbara --------------------
        self.akcje_toolbara = []
        # koniec akcji ----------------------

        # ikony -----------------------------
        ico_wydz_dopisz = QIcon(os.path.join(self.plugin_dir,
                                             'ico',
                                             'wydz_dopisz.png'))
        ico_wydz_rys_zab = QIcon(os.path.join(self.plugin_dir,
                                              'ico',
                                              'wydz_rys_zab.png'))
        ico_wydz_rys_gat = QIcon(os.path.join(self.plugin_dir,
                                              'ico',
                                              'wydz_rys_gat.png'))
        ico_wydz_rys_orto = QIcon(os.path.join(self.plugin_dir,
                                               'ico',
                                               'wydz_rys_orto.png'))
        ico_wydz_rys_stl = QIcon(os.path.join(self.plugin_dir,
                                              'ico',
                                              'wydz_rys_stl.png'))
        ico_topo = QIcon(os.path.join(self.plugin_dir,
                                      'ico',
                                      'spr_topo.png'))
        ico_wydz_spr = QIcon(os.path.join(self.plugin_dir,
                                          'ico',
                                          'wydz_sprawdz.png'))
        # koniec ikon -----------------------

        self.menu = QMenu(self.iface.mainWindow())
        self.menu.setObjectName('LAS-R')
        self.menu.setTitle('LAS-R')

        menuBar = self.iface.mainWindow().menuBar()
        menuBar.insertMenu(self.iface.firstRightStandardMenu().menuAction(),
                           self.menu)

        self.baza_taks = QMenu(u'Baza Taksatora', self.menu)
        self.przyg_danych = QMenu(u'Przygotowanie danych', self.menu)
        self.spr_danych = QMenu(u'Sprawdzenie danych', self.menu)

        self.menu.addMenu(self.baza_taks)
        self.menu.addMenu(self.przyg_danych)
        self.menu.addMenu(self.spr_danych)

        self.przyg_dzewid = QAction(QIcon(None),
                                    u"Przygotuj działki ewidencyjne",
                                    self.iface.mainWindow())
        self.przyg_danych.addAction(self.przyg_dzewid)
        self.przyg_dzewid.triggered.connect(self.przygotuj_dzewid)

        self.przyg_ls = QAction(QIcon(None),
                                u"Przygotuj Lsy",
                                self.iface.mainWindow())
        self.przyg_danych.addAction(self.przyg_ls)
        self.przyg_ls.triggered.connect(self.przygotuj_ls)

        self.wyz_lz = QAction(QIcon(None),
                              'LZ - wyznacz potencjalne',
                              self.iface.mainWindow())
        self.przyg_danych.addAction(self.wyz_lz)
        self.wyz_lz.triggered.connect(self.wyszukaj_lz)

        self.przyg_ciec = QAction(QIcon(None),
                                  u"Przygotuj wydzielenia do cięcia",
                                  self.iface.mainWindow())
        self.przyg_danych.addAction(self.przyg_ciec)

        self.przyg_danych.addSeparator()

        self.przyg_ciec.triggered.connect(self.przygotuj_do_ciecia)

        self.zanum = QAction(QIcon(None),
                             'Zanumeruj oddziały',
                             self.iface.mainWindow())
        self.przyg_danych.addAction(self.zanum)
        self.zanum.triggered.connect(self.zanumeruj)

        self.dop_w_o = QAction(QIcon(None),
                               'Dopisz oddziały do wydzieleń',
                               self.iface.mainWindow())
        self.przyg_danych.addAction(self.dop_w_o)
        self.dop_w_o.triggered.connect(self.dopisz_wydz_w_oddz)

        self.zalit = QAction(QIcon(None),
                             'Zaliterkuj wydzielenia',
                             self.iface.mainWindow())
        self.przyg_danych.addAction(self.zalit)
        self.zalit.triggered.connect(self.zaliterkuj)

        self.dop_adrles = QAction(QIcon(None),
                                  'Zaadresuj [ADR_LES]',
                                  self.iface.mainWindow())
        self.przyg_danych.addAction(self.dop_adrles)
        self.dop_adrles.triggered.connect(self.dopisz_adrles)

        self.przyg_danych.addSeparator()

        self.eksp_kml = QAction(QIcon(None),
                                u"Wyeksportuj do KML",
                                self.iface.mainWindow())
        self.przyg_danych.addAction(self.eksp_kml)
        self.eksp_kml.triggered.connect(self.eksportuj_do_KML)

        self.rozlicz_wydz = QAction(QIcon(None),
                                    'Rozlicz powierzchnię wydz.',
                                    self.iface.mainWindow())
        self.baza_taks.addAction(self.rozlicz_wydz)
        self.rozlicz_wydz.triggered.connect(self.rozlicz_pow_wydzielen)

        self.dop_fo = QAction(QIcon(None),
                              'Dopisz formy ochrony',
                              self.iface.mainWindow())
        self.baza_taks.addAction(self.dop_fo)
        self.dop_fo.triggered.connect(self.dopisz_f_ochr)

        self.spr_w_o = QAction(QIcon(None),
                               'Sprawdź wydzielenia w oddziałach',
                               self.iface.mainWindow())
        self.spr_danych.addAction(self.spr_w_o)
        self.spr_w_o.triggered.connect(self.sprawdz_wydz_w_oddz)

        self.spr_wydz = QAction(ico_wydz_spr,
                                'Sprawdź wydzielenia',
                                self.iface.mainWindow())
        self.spr_danych.addAction(self.spr_wydz)
        self.spr_wydz.triggered.connect(self.sprawdzenie_wydzielen)

        self.spr_topo = QAction(ico_topo,
                                'Sprawdź topologię',
                                self.iface.mainWindow())
        self.spr_danych.addAction(self.spr_topo)
        self.spr_topo.triggered.connect(self.sprawdz_topologie)

        self.menu.addSeparator()

        self.dop_wydz = QAction(ico_wydz_dopisz,
                                'Dopisz do wydzieleń',
                                self.iface.mainWindow())
        self.menu.addAction(self.dop_wydz)
        self.dop_wydz.triggered.connect(self.dopisanie_wydzielen)

        self.nakl = QAction(QIcon(None),
                            'Generuj naklejki',
                            self.iface.mainWindow())
        self.menu.addAction(self.nakl)
        self.nakl.triggered.connect(self.rysuj_naklejki)

        # toolbar -----------------------------
        self.dop_meta = QAction(ico_wydz_dopisz,
                                'Dopisz metadane',
                                self.iface.mainWindow())
        self.toolbar.addAction(self.dop_meta)
        self.dop_meta.triggered.connect(self.dopisanie_wydzielen)

        self.toolbar.addAction(self.spr_wydz)

        self.toolbar.addSeparator()

        self.rys_gat = QAction(ico_wydz_rys_gat,
                               'Rysuj gatunki',
                               self.iface.mainWindow())
        self.toolbar.addAction(self.rys_gat)
        self.rys_gat.triggered.connect(self.rysuj_gatunki)

        self.rys_zab = QAction(ico_wydz_rys_zab,
                               'Rysuj zabiegi',
                               self.iface.mainWindow())
        self.toolbar.addAction(self.rys_zab)
        self.rys_zab.triggered.connect(self.rysuj_zabiegi)

        self.rys_stl = QAction(ico_wydz_rys_stl,
                               'Rysuj STL',
                               self.iface.mainWindow())
        self.toolbar.addAction(self.rys_stl)
        self.rys_stl.triggered.connect(self.rysuj_stl)

        self.rys_orto = QAction(ico_wydz_rys_orto,
                                'Rysuj na orto',
                                self.iface.mainWindow())
        self.toolbar.addAction(self.rys_orto)
        self.rys_orto.triggered.connect(self.rysuj_orto)

        self.toolbar.addSeparator()

        self.toolbar.addAction(self.spr_topo)

        self.akcje_toolbara = [self.dop_meta,
                               self.spr_wydz,
                               self.rys_stl,
                               self.rys_gat,
                               self.rys_zab,
                               self.rys_orto,
                               self.spr_topo
                               ]
        # toolbar koniec ---------------------

        # self.menu.addSeparator()
        # icon_path = ':/plugins/las_r/icon.png'
        # self.add_action(
        #     icon_path,
        #     text=self.tr(u'Las-R'),
        #     callback=self.run,
        #     parent=self.iface.mainWindow())

    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        # for action in self.actions:
        #     self.iface.removePluginMenu(
        #         self.tr(u'&Las-R'),
        #         action)
        #     self.iface.removeToolBarIcon(action)
        # remove the toolbar
        if self.menu is not None:
            self.iface.mainWindow().menuBar().removeAction(
                self.menu.menuAction())
        for a in self.akcje_toolbara:
            self.iface.removeToolBarIcon(a)
        # del self.toolbar

    def run(self):
        """Run method that performs all the real work"""
        # show the dialog
        # self.dlg.show()
        # Run the dialog event loop
        # result = self.dlg.exec_()
        # See if OK was pressed
        # if result:
        #    Do something useful here - delete the line containing pass and
        #    substitute with your code.
        #    pass
        pass

    def przygotuj_dzewid(self):
        sprawdz_dzkat.SprawdzDzKat(self.iface)

    def przygotuj_ls(self):
        spr = sprawdz_ls.SprawdzLs(self.iface)
        if not spr.sprawdz_warstwy():
            return
        if not spr.wczytaj():
            return
        spr.sprawdz()
        spr.przygotuj()
        spr.przetworz()

    def dopisz_f_ochr(self):
        b = baza_dopisz_fochr.DopiszFO(self.iface)
        if not b.pobierz_dane_od_uzytkownika():
            return
        if not b.poprawne_wydz():
            return False
        if not b.poprawne_fo():
            return False
        if b.wybierz_fo():
            b.wybierz_wydz()
            b.dopisz_do_bazy()

    def rozlicz_pow_wydzielen(self):
        b = baza_rozlicz_pow_wydz.RozliczPowierzchnieWydz(self.iface)
        if not b.sprawdz_dane():
            return
        b.przetnij_wydz_ls()
        if b.zbuduj_strukture():
            b.sprawdz_rozlicz_graf()
            b.zestaw_rozliczenie()
            b.zapisz_rozliczenie()  # wypisz do csv do sprawdzenia
            if not b.dopisz_rozliczenie():
                return
            else:
                b.sprawdz_rozlicz_rej()
                b.skasuj_robocze()

    def sprawdz_topologie(self):
        b = sprawdzenia_topo.SprawdzTopo(self.iface)
        b.pobierz_feat()
        b.spr_wstepne()
        b.spr_styki()
        b.spr_wasy()
        b.spr_nakladanie()
        b.dodaj_warstwy()

    def sprawdzenie_wydzielen(self):
        k = spr_wydzielen.KontrolaWydzielen(self.iface)
        if k.poprawne_wydz():
            k.sprawdz_odl_wydz()
            k.sprawdz_odl_lz()
            k.pokaz_bledy()

    def dopisanie_wydzielen(self):
        d = shp_dopisz_kody.DopiszKody(self.iface)
        if d.pobierz_dane():
            if d.poprawne_wydz():
                if d.pobierzBaze():
                    d.dopisz_kody()

    def dopisz_adrles(self):
        shp_adr_les.zaadresuj(self.iface)

    def dopisz_wydz_w_oddz(self):
        shp_dopOddzWydz.dopOddzWydz(self.iface)

    def przygotuj_do_ciecia(self):
        shp_przygCiecie.przygotujDoCiecia(self.iface)

    def zaliterkuj(self):
        shp_literkuj.Literkuj(self.iface)

    def zanumeruj(self):
        shp_numeruj.Numeruj(self.iface)

    def sprawdz_wydz_w_oddz(self):
        shp_sprWydzOddz.SprWydzOddz(self.iface)

    def eksportuj_do_KML(self):
        s = shp_eksport_kml.EksportujKML(self.iface)
        if s.pobierzDane():
            s.przetworz()
            s.zapisz_kml()

    def wyszukaj_lz(self):
        lz = shp_wyszukaj_lz.WyszukajLz(self.iface)
        if lz.pobierz_dane():
            lz.zabuduj_strukt()
            lz.wybierz_potencjalne_lz()
            lz.stworz_warstwe_lz()

    def rysuj_naklejki(self):
        n = naklejki.GenerujNaklejki(self.iface)

        # jeżeli w projekcie sa inne layout i uzytkownik nie chce kontynuowac
        # to przerywamy procedure
        if n.inne_layouty():
            return

        if n.pobierz_dane():
            n.generuj_all()

    def rysuj_gatunki(self):
        shp_symbolizacja.rysuj(self.iface, 'gat')

    def rysuj_zabiegi(self):
        shp_symbolizacja.rysuj(self.iface, 'zab')

    def rysuj_orto(self):
        shp_symbolizacja.rysuj(self.iface, 'orto')

    def rysuj_stl(self):
        shp_symbolizacja.rysuj(self.iface, 'stl')
