# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_naklejki_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_DialogNaklejki(object):
    def setupUi(self, DialogNaklejki):
        DialogNaklejki.setObjectName("DialogNaklejki")
        DialogNaklejki.resize(467, 296)
        DialogNaklejki.setMinimumSize(QtCore.QSize(467, 296))
        DialogNaklejki.setMaximumSize(QtCore.QSize(467, 296))
        self.buttonBox = QtWidgets.QDialogButtonBox(DialogNaklejki)
        self.buttonBox.setGeometry(QtCore.QRect(370, 110, 81, 81))
        self.buttonBox.setMaximumSize(QtCore.QSize(81, 241))
        self.buttonBox.setOrientation(QtCore.Qt.Vertical)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.pushButton_wybierz = QtWidgets.QPushButton(DialogNaklejki)
        self.pushButton_wybierz.setGeometry(QtCore.QRect(370, 30, 75, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.pushButton_wybierz.setFont(font)
        self.pushButton_wybierz.setObjectName("pushButton_wybierz")
        self.lineEdit_sciezka = QtWidgets.QLineEdit(DialogNaklejki)
        self.lineEdit_sciezka.setGeometry(QtCore.QRect(20, 30, 341, 20))
        self.lineEdit_sciezka.setObjectName("lineEdit_sciezka")
        self.label = QtWidgets.QLabel(DialogNaklejki)
        self.label.setGeometry(QtCore.QRect(30, 10, 211, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(DialogNaklejki)
        self.label_2.setGeometry(QtCore.QRect(40, 160, 171, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lineEdit_od = QtWidgets.QLineEdit(DialogNaklejki)
        self.lineEdit_od.setGeometry(QtCore.QRect(50, 180, 111, 20))
        self.lineEdit_od.setObjectName("lineEdit_od")
        self.label_3 = QtWidgets.QLabel(DialogNaklejki)
        self.label_3.setGeometry(QtCore.QRect(30, 180, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(DialogNaklejki)
        self.label_4.setGeometry(QtCore.QRect(190, 180, 21, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.lineEdit_do = QtWidgets.QLineEdit(DialogNaklejki)
        self.lineEdit_do.setGeometry(QtCore.QRect(220, 180, 111, 20))
        self.lineEdit_do.setObjectName("lineEdit_do")
        self.label_5 = QtWidgets.QLabel(DialogNaklejki)
        self.label_5.setGeometry(QtCore.QRect(20, 60, 131, 16))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.comboBox_typ = QtWidgets.QComboBox(DialogNaklejki)
        self.comboBox_typ.setGeometry(QtCore.QRect(170, 60, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.comboBox_typ.setFont(font)
        self.comboBox_typ.setObjectName("comboBox_typ")
        self.comboBox_typ.addItem("")
        self.comboBox_typ.addItem("")
        self.checkBox_polacz = QtWidgets.QCheckBox(DialogNaklejki)
        self.checkBox_polacz.setEnabled(False)
        self.checkBox_polacz.setGeometry(QtCore.QRect(50, 100, 191, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_polacz.setFont(font)
        self.checkBox_polacz.setObjectName("checkBox_polacz")
        self.checkBox_tomy = QtWidgets.QCheckBox(DialogNaklejki)
        self.checkBox_tomy.setGeometry(QtCore.QRect(50, 130, 281, 22))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.checkBox_tomy.setFont(font)
        self.checkBox_tomy.setObjectName("checkBox_tomy")
        self.label_6 = QtWidgets.QLabel(DialogNaklejki)
        self.label_6.setGeometry(QtCore.QRect(40, 200, 311, 18))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setItalic(True)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.groupBox = QtWidgets.QGroupBox(DialogNaklejki)
        self.groupBox.setGeometry(QtCore.QRect(20, 230, 431, 61))
        font = QtGui.QFont()
        font.setFamily("Arial")
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.checkBox_plyta = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_plyta.setGeometry(QtCore.QRect(30, 30, 87, 22))
        self.checkBox_plyta.setChecked(True)
        self.checkBox_plyta.setObjectName("checkBox_plyta")
        self.checkBox_okladka = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_okladka.setGeometry(QtCore.QRect(170, 30, 87, 22))
        self.checkBox_okladka.setChecked(True)
        self.checkBox_okladka.setObjectName("checkBox_okladka")
        self.checkBox_naklejki = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_naklejki.setGeometry(QtCore.QRect(300, 30, 87, 22))
        self.checkBox_naklejki.setChecked(True)
        self.checkBox_naklejki.setObjectName("checkBox_naklejki")

        self.retranslateUi(DialogNaklejki)
        self.buttonBox.accepted.connect(DialogNaklejki.accept)
        self.buttonBox.rejected.connect(DialogNaklejki.reject)
        QtCore.QMetaObject.connectSlotsByName(DialogNaklejki)

    def retranslateUi(self, DialogNaklejki):
        _translate = QtCore.QCoreApplication.translate
        DialogNaklejki.setWindowTitle(_translate("DialogNaklejki", "Podaj informacje do generowania naklejek"))
        self.pushButton_wybierz.setText(_translate("DialogNaklejki", "Wybierz"))
        self.label.setText(_translate("DialogNaklejki", "Katalog z bazami taksatora:"))
        self.label_2.setText(_translate("DialogNaklejki", "Stan na:"))
        self.lineEdit_od.setText(_translate("DialogNaklejki", "DD.MM.RRRR"))
        self.label_3.setText(_translate("DialogNaklejki", "od:"))
        self.label_4.setText(_translate("DialogNaklejki", "do:"))
        self.lineEdit_do.setText(_translate("DialogNaklejki", "DD.MM.RRRR"))
        self.label_5.setText(_translate("DialogNaklejki", "Typ opracowania:"))
        self.comboBox_typ.setItemText(0, _translate("DialogNaklejki", "UPUL"))
        self.comboBox_typ.setItemText(1, _translate("DialogNaklejki", "ISL"))
        self.checkBox_polacz.setText(_translate("DialogNaklejki", "Połączony dla całej gminy"))
        self.checkBox_tomy.setText(_translate("DialogNaklejki", "opracowania są podzielone na tomy"))
        self.label_6.setText(_translate("DialogNaklejki", "Stan geodezji zostanie podczytany z bazy TPU"))
        self.groupBox.setTitle(_translate("DialogNaklejki", "Generuj"))
        self.checkBox_plyta.setText(_translate("DialogNaklejki", "płytkę"))
        self.checkBox_okladka.setText(_translate("DialogNaklejki", "okładkę"))
        self.checkBox_naklejki.setText(_translate("DialogNaklejki", "naklejki"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DialogNaklejki = QtWidgets.QDialog()
    ui = Ui_DialogNaklejki()
    ui.setupUi(DialogNaklejki)
    DialogNaklejki.show()
    sys.exit(app.exec_())

